version: "3.7"


volumes:
  testd-pg-data:
    name: testd-pg-data

services:
  postgres:
    image: postgres:10-alpine
    container_name: test-postgres
    restart: always
    ports:
    - 5432:5432
    volumes:
    - type: volume
      source: testd-pg-data
      target: /var/lib/postgresql/data
    environment:
      POSTGRES_DB: testd
      POSTGRES_PASSWORD: postgres

  server:
    container_name: testd-server
    restart: always
    ports:
    - 3000:3000
    build: .
    volumes:
    - ./.env:/home/node/.env
    - ./src:/home/node/src
    - /home/node/node_modules
    links:
    - postgres
    environment:
      DEV_ENV: 'docker'